### ISSUE TITLE
enable opting out of ascii encoding

### ISSUE THREAD

**Issue by jesseduffield** [livebg/smstools#6]
I can't find anywhere on the internet that suggests carriers support ascii encoding. It looks like it was added to this repo as a restricted form of the GSM-7 encoding, however with the ascii encoding we get slightly different behaviour. For example, in ascii, unlike GSM-7, we don't escape characters like `[` and `]` meaning we can end up with shorter messages.

I'm not sure what the original intention was behind adding ascii support. If it was to just define a restricted set of GSM-7 characters before switching to UCS-2, then I think we should still treat characters like `[` as requiring an escape character regardless of whether we're in ascii or GSM-7 encoding. Otherwise I think we should allow opting out of ascii encoding. Happy to do the PR myself :)

**Comment by mitio** [comment]
Hey @jesseduffield, thanks for raising this! Looking through the code, seems like this change was introduced in f1ffd948d4b8c778b4005c8aa8d6ada9fc2197d7. The commit message has some details on why the "ascii" encoding was added.

I agree with your suggestion to allow opting out of the ASCII encoding. Probably something similar to what we have for the GSM encoding already – `SmsTools.use_ascii_encoding = false`. PRs welcome! 😄 

You're correct that in general, on the wire, the ASCII message will be sent as either Unicode, or GSM 03.38 and if it's the latter, then its length would be governed by the same rules. So I'd agree with you that the length of the message should probably be computed using the same rules as in GSM 03.38. But I'd rather opt for allowing disabling the ASCII encoding detection instead of changing the logic of how the length is counted in these cases.

**Comment by jesseduffield** [comment]
Sounds good.

After cloning the repo and running `bundle install` I'm getting this error upon running `bundle exec rake test`:
```
Traceback (most recent call last):
	9: from /Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:5:in `<main>'
	8: from /Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:5:in `select'
	7: from /Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	6: from /Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:17:in `require'
	5: from /Users/jesseduffieldduffield/ap/smstools/spec/sms_tools/encoding_detection_spec.rb:1:in `<top (required)>'
	4: from /Users/jesseduffieldduffield/ap/smstools/spec/sms_tools/encoding_detection_spec.rb:1:in `require'
	3: from /Users/jesseduffieldduffield/ap/smstools/spec/spec_helper.rb:8:in `<top (required)>'
	2: from /Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-ansi-0.1.2/lib/minitest/ansi.rb:47:in `use!'
	1: from /Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-ansi-0.1.2/lib/minitest/ansi.rb:47:in `new'
/Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-ansi-0.1.2/lib/minitest/ansi.rb:18:in `initialize': undefined method `output' for Minitest::Unit:Class (NoMethodError)
rake aborted!
Command failed with status (1): [ruby -w -I"lib:spec" -I"/Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib" "/Users/jesseduffieldduffield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb" "spec/sms_tools/encoding_detection_spec.rb" "spec/sms_tools/gsm_encoding_spec.rb" ]
/Users/jesseduffieldduffield/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/jesseduffieldduffield/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

Perhaps the minitest version used is now outdated? I noticed that in the gemspec no version is specified for it, so I'm guessing my fairly new version is out of sync with what the code currently expects.

**Comment by jesseduffield** [comment]
@mitio do you know how we might be able to resolve this issue?

**Comment by mitio** [comment]
Hey, apologies for the delay, I'll have a look asap at let you know.

**Comment by kingsley-wang** [comment]
Hey @mitio , just raised a [pr](https://github.com/livebg/smstools/pull/7) for introducing `use_ascii_encoding` for both Server-side and Client-side. Also, added some tests to cover the updates, and all tests passed. Please have a check.

**Comment by mitio** [comment]
@kingsley-wang @jesseduffield thanks for the contribution!

Version 0.2.1 has been released and it should address this. Closing the issue for now. Feel free to reopen if you think there's more to do here.

**Comment by jesseduffield** [comment]
Thanks @mitio !

**Comment by kingsley-wang** [comment]
Thanks @mitio !
